# Generated by Django 4.2 on 2026-05-31 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LeccionAprendida',
            fields=[
                ('id_leccion_aprendida', models.AutoField(db_column='ID_LECCION_APRENDIDA', primary_key=True, serialize=False)),
                ('tipo', models.CharField(blank=True, db_column='TIPO', max_length=100, null=True)),
                ('descripcion', models.TextField(blank=True, db_column='DESCRIPCION', null=True)),
                ('fecha_identificacion', models.DateField(blank=True, db_column='FECHA_IDENTIFICACION', null=True)),
                ('impacto_situacion', models.TextField(blank=True, db_column='IMPACTO_SITUACION', null=True)),
                ('recomendacion', models.TextField(blank=True, db_column='RECOMENDACION', null=True)),
                ('accion_tomar', models.TextField(blank=True, db_column='ACCION_TOMAR', null=True)),
                ('justificacion', models.TextField(blank=True, db_column='JUSTIFICACION', null=True)),
                ('nivel_eficacia', models.CharField(blank=True, db_column='NIVEL_EFICACIA', max_length=20, null=True)),
                ('id_reporte', models.CharField(blank=True, db_column='ID_REPORTE', max_length=100, null=True)),
            ],
            options={
                'db_table': 'LECCION_APRENDIDA',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ReporteSeguridad',
            fields=[
                ('id_reporte', models.AutoField(db_column='ID_REPORTE', primary_key=True, serialize=False)),
                ('id_usuario', models.IntegerField(blank=True, db_column='ID_USUARIO', null=True)),
                ('fecha_reporte', models.DateTimeField(auto_now_add=True, db_column='FECHA_REPORTE')),
                ('estado', models.CharField(blank=True, db_column='ESTADO', max_length=50, null=True)),
            ],
            options={
                'db_table': 'REPORTE_DE_SEGURIDAD',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RiesgoSeguridad',
            fields=[
                ('id_rsf', models.AutoField(db_column='ID_RSF', primary_key=True, serialize=False)),
                ('id_reporte', models.CharField(blank=True, db_column='ID_REPORTE', max_length=100, null=True)),
                ('origen_mejora', models.TextField(blank=True, db_column='ORIGEN_MEJORA', null=True)),
                ('responsable_seguimiento', models.CharField(blank=True, db_column='RESPONSABLE_SEGUIMIENTO', max_length=200, null=True)),
                ('macroproceso', models.CharField(blank=True, db_column='MACROPROCESO', max_length=200, null=True)),
                ('actividad', models.TextField(blank=True, db_column='ACTIVIDAD', null=True)),
                ('area', models.CharField(blank=True, db_column='AREA', max_length=200, null=True)),
                ('recomendacion', models.TextField(blank=True, db_column='RECOMENDACION', null=True)),
                ('dependencia', models.CharField(blank=True, db_column='DEPENDENCIA', max_length=200, null=True)),
                ('nivel_riesgo', models.CharField(blank=True, db_column='NIVEL_RIESGO', max_length=20, null=True)),
            ],
            options={
                'db_table': 'RIESGO_DE_SEGURIDAD',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id_rol', models.AutoField(db_column='ID_ROL', primary_key=True, serialize=False)),
                ('nombre_rol', models.CharField(db_column='NOMBRE_ROL', max_length=100, unique=True)),
                ('estado', models.BooleanField(db_column='ESTADO', default=True)),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
                'db_table': 'ROL',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id_usuario', models.AutoField(db_column='ID_USUARIO', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='NOMBRE', max_length=255)),
                ('apellido', models.CharField(db_column='APELLIDO', max_length=255)),
                ('correo', models.CharField(db_column='CORREO', max_length=255)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, db_column='FECHA_REGISTRO')),
                ('contrasena', models.CharField(db_column='CONTRASENA', max_length=255)),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'USUARIOS',
                'managed': False,
            },
        ),
    ]
