# Generated by Django 4.2 on 2026-06-10 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('f37', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BitacoraAuditoria',
            fields=[
                ('id_auditoria', models.AutoField(db_column='ID_AUDITORIA', primary_key=True, serialize=False)),
                ('usuario', models.CharField(db_column='USUARIO', max_length=150)),
                ('accion', models.CharField(db_column='ACCION', max_length=50)),
                ('modulo', models.CharField(db_column='MODULO', max_length=100)),
                ('detalle', models.TextField(db_column='DETALLE')),
                ('fecha_accion', models.DateTimeField(auto_now_add=True, db_column='FECHA_ACCION')),
            ],
            options={
                'verbose_name': 'Auditoría',
                'verbose_name_plural': 'Auditorías',
                'db_table': 'BITACORA_AUDITORIA',
                'managed': True,
            },
        ),
    ]
