# Generated by Django 6.0.3 on 2026-06-13 04:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('f37', '0002_bitacoraauditoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeguimientoLeccion',
            fields=[
                ('id_seguimiento', models.AutoField(db_column='ID_SEGUIMIENTO', primary_key=True, serialize=False)),
                ('comentario', models.TextField(db_column='COMENTARIO')),
                ('fecha_seguimiento', models.DateTimeField(auto_now_add=True, db_column='FECHA_SEGUIMIENTO')),
                ('estado_anterior', models.CharField(blank=True, db_column='ESTADO_ANTERIOR', max_length=50, null=True)),
                ('estado_nuevo', models.CharField(blank=True, db_column='ESTADO_NUEVO', max_length=50, null=True)),
                ('id_leccion', models.ForeignKey(db_column='ID_LECCION', on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos', to='f37.leccionaprendida')),
                ('id_usuario', models.ForeignKey(db_column='ID_USUARIO', on_delete=django.db.models.deletion.CASCADE, to='f37.usuarios')),
            ],
            options={
                'verbose_name': 'Seguimiento de Lección',
                'verbose_name_plural': 'Seguimientos de Lecciones',
                'db_table': 'SEGUIMIENTO_LECCION',
                'managed': True,
            },
        ),
    ]
